name: first-workflow

on: push

jobs: 
  send-restic-pack:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.1.0 #gets the source code into the vm
      - uses: actions/setup-go@v3.2.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ppc64le
          distro: ubuntu20.04
          run: | 
            bash before_script.sh
            python3 ftp_version.py
            bash build.sh
            bash release.sh
